
// This file has been generated by the GUI designer. Do not modify.
namespace KontrolniZadatak
{
	public partial class MyMessageBox
	{
		private global::Gtk.TextView textview2;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget KontrolniZadatak.MyMessageBox
			this.Name = "KontrolniZadatak.MyMessageBox";
			this.Title = global::Mono.Unix.Catalog.GetString("MyMessageBox");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child KontrolniZadatak.MyMessageBox.Gtk.Container+ContainerChild
			this.textview2 = new global::Gtk.TextView();
			this.textview2.CanFocus = true;
			this.textview2.Name = "textview2";
			this.textview2.Editable = false;
			this.textview2.CursorVisible = false;
			this.Add(this.textview2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
