
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Table table1;

	private global::Gtk.Label BrojIndex;

	private global::Gtk.Calendar calendar;

	private global::Gtk.ComboBox combobox1;

	private global::Gtk.Label datumRodjenja;

	private global::Gtk.Button dodaj;

	private global::Gtk.HBox hbox1;

	private global::Gtk.RadioButton radiobutton2;

	private global::Gtk.RadioButton radiobutton3;

	private global::Gtk.Label ime;

	private global::Gtk.Label imeRoditelja;

	private global::Gtk.Label label9;

	private global::Gtk.Label Pol;

	private global::Gtk.Label Prezime;

	private global::Gtk.Label Smer;

	private global::Gtk.Button studenti;

	private global::Gtk.TextView tbrojIndex;

	private global::Gtk.TextView tgodina;

	private global::Gtk.TextView tIme;

	private global::Gtk.TextView timeRoditelja;

	private global::Gtk.TextView tprezime;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.table1 = new global::Gtk.Table(((uint)(9)), ((uint)(2)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.BrojIndex = new global::Gtk.Label();
		this.BrojIndex.Name = "BrojIndex";
		this.BrojIndex.LabelProp = global::Mono.Unix.Catalog.GetString("BrojIndex");
		this.table1.Add(this.BrojIndex);
		global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1[this.BrojIndex]));
		w1.XOptions = ((global::Gtk.AttachOptions)(4));
		w1.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.calendar = new global::Gtk.Calendar();
		this.calendar.CanFocus = true;
		this.calendar.Name = "calendar";
		this.calendar.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
		this.table1.Add(this.calendar);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1[this.calendar]));
		w2.TopAttach = ((uint)(3));
		w2.BottomAttach = ((uint)(4));
		w2.LeftAttach = ((uint)(1));
		w2.RightAttach = ((uint)(2));
		w2.XOptions = ((global::Gtk.AttachOptions)(4));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.combobox1 = global::Gtk.ComboBox.NewText();
		this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("E1"));
		this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("E2"));
		this.combobox1.AppendText(global::Mono.Unix.Catalog.GetString("E3"));
		this.combobox1.Name = "combobox1";
		this.table1.Add(this.combobox1);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1[this.combobox1]));
		w3.TopAttach = ((uint)(6));
		w3.BottomAttach = ((uint)(7));
		w3.LeftAttach = ((uint)(1));
		w3.RightAttach = ((uint)(2));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.datumRodjenja = new global::Gtk.Label();
		this.datumRodjenja.Name = "datumRodjenja";
		this.datumRodjenja.LabelProp = global::Mono.Unix.Catalog.GetString("datumRodjenja");
		this.table1.Add(this.datumRodjenja);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1[this.datumRodjenja]));
		w4.TopAttach = ((uint)(3));
		w4.BottomAttach = ((uint)(4));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.dodaj = new global::Gtk.Button();
		this.dodaj.CanFocus = true;
		this.dodaj.Name = "dodaj";
		this.dodaj.UseUnderline = true;
		this.dodaj.Label = global::Mono.Unix.Catalog.GetString("Dodaj ucenika");
		this.table1.Add(this.dodaj);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.dodaj]));
		w5.TopAttach = ((uint)(8));
		w5.BottomAttach = ((uint)(9));
		w5.LeftAttach = ((uint)(1));
		w5.RightAttach = ((uint)(2));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.radiobutton2 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Muski"));
		this.radiobutton2.CanFocus = true;
		this.radiobutton2.Name = "radiobutton2";
		this.radiobutton2.DrawIndicator = true;
		this.radiobutton2.UseUnderline = true;
		this.radiobutton2.Group = new global::GLib.SList(global::System.IntPtr.Zero);
		this.hbox1.Add(this.radiobutton2);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.radiobutton2]));
		w6.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.radiobutton3 = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Zenski"));
		this.radiobutton3.CanFocus = true;
		this.radiobutton3.Name = "radiobutton3";
		this.radiobutton3.DrawIndicator = true;
		this.radiobutton3.UseUnderline = true;
		this.radiobutton3.Group = this.radiobutton2.Group;
		this.hbox1.Add(this.radiobutton3);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.radiobutton3]));
		w7.Position = 1;
		this.table1.Add(this.hbox1);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1[this.hbox1]));
		w8.TopAttach = ((uint)(5));
		w8.BottomAttach = ((uint)(6));
		w8.LeftAttach = ((uint)(1));
		w8.RightAttach = ((uint)(2));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.ime = new global::Gtk.Label();
		this.ime.Name = "ime";
		this.ime.LabelProp = global::Mono.Unix.Catalog.GetString("Ime");
		this.table1.Add(this.ime);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1[this.ime]));
		w9.TopAttach = ((uint)(1));
		w9.BottomAttach = ((uint)(2));
		w9.XOptions = ((global::Gtk.AttachOptions)(4));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.imeRoditelja = new global::Gtk.Label();
		this.imeRoditelja.Name = "imeRoditelja";
		this.imeRoditelja.LabelProp = global::Mono.Unix.Catalog.GetString("imeRoditelja");
		this.table1.Add(this.imeRoditelja);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1[this.imeRoditelja]));
		w10.TopAttach = ((uint)(4));
		w10.BottomAttach = ((uint)(5));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label9 = new global::Gtk.Label();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Godina");
		this.table1.Add(this.label9);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1[this.label9]));
		w11.TopAttach = ((uint)(7));
		w11.BottomAttach = ((uint)(8));
		w11.XOptions = ((global::Gtk.AttachOptions)(4));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.Pol = new global::Gtk.Label();
		this.Pol.Name = "Pol";
		this.Pol.LabelProp = global::Mono.Unix.Catalog.GetString("pol");
		this.table1.Add(this.Pol);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1[this.Pol]));
		w12.TopAttach = ((uint)(5));
		w12.BottomAttach = ((uint)(6));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.Prezime = new global::Gtk.Label();
		this.Prezime.Name = "Prezime";
		this.Prezime.LabelProp = global::Mono.Unix.Catalog.GetString("prezime");
		this.table1.Add(this.Prezime);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1[this.Prezime]));
		w13.TopAttach = ((uint)(2));
		w13.BottomAttach = ((uint)(3));
		w13.XOptions = ((global::Gtk.AttachOptions)(4));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.Smer = new global::Gtk.Label();
		this.Smer.Name = "Smer";
		this.Smer.LabelProp = global::Mono.Unix.Catalog.GetString("Smer");
		this.table1.Add(this.Smer);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1[this.Smer]));
		w14.TopAttach = ((uint)(6));
		w14.BottomAttach = ((uint)(7));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.studenti = new global::Gtk.Button();
		this.studenti.CanFocus = true;
		this.studenti.Name = "studenti";
		this.studenti.UseUnderline = true;
		this.studenti.Label = global::Mono.Unix.Catalog.GetString("Studenti");
		this.table1.Add(this.studenti);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1[this.studenti]));
		w15.TopAttach = ((uint)(8));
		w15.BottomAttach = ((uint)(9));
		w15.XOptions = ((global::Gtk.AttachOptions)(4));
		w15.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.tbrojIndex = new global::Gtk.TextView();
		this.tbrojIndex.CanFocus = true;
		this.tbrojIndex.Name = "tbrojIndex";
		this.tbrojIndex.AcceptsTab = false;
		this.table1.Add(this.tbrojIndex);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1[this.tbrojIndex]));
		w16.LeftAttach = ((uint)(1));
		w16.RightAttach = ((uint)(2));
		w16.XOptions = ((global::Gtk.AttachOptions)(4));
		w16.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.tgodina = new global::Gtk.TextView();
		this.tgodina.CanFocus = true;
		this.tgodina.Name = "tgodina";
		this.tgodina.AcceptsTab = false;
		this.table1.Add(this.tgodina);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1[this.tgodina]));
		w17.TopAttach = ((uint)(7));
		w17.BottomAttach = ((uint)(8));
		w17.LeftAttach = ((uint)(1));
		w17.RightAttach = ((uint)(2));
		w17.XOptions = ((global::Gtk.AttachOptions)(4));
		w17.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.tIme = new global::Gtk.TextView();
		this.tIme.CanFocus = true;
		this.tIme.Name = "tIme";
		this.tIme.AcceptsTab = false;
		this.table1.Add(this.tIme);
		global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table1[this.tIme]));
		w18.TopAttach = ((uint)(1));
		w18.BottomAttach = ((uint)(2));
		w18.LeftAttach = ((uint)(1));
		w18.RightAttach = ((uint)(2));
		w18.XOptions = ((global::Gtk.AttachOptions)(4));
		w18.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.timeRoditelja = new global::Gtk.TextView();
		this.timeRoditelja.CanFocus = true;
		this.timeRoditelja.Name = "timeRoditelja";
		this.timeRoditelja.AcceptsTab = false;
		this.table1.Add(this.timeRoditelja);
		global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table1[this.timeRoditelja]));
		w19.TopAttach = ((uint)(4));
		w19.BottomAttach = ((uint)(5));
		w19.LeftAttach = ((uint)(1));
		w19.RightAttach = ((uint)(2));
		w19.XOptions = ((global::Gtk.AttachOptions)(4));
		w19.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.tprezime = new global::Gtk.TextView();
		this.tprezime.CanFocus = true;
		this.tprezime.Name = "tprezime";
		this.tprezime.AcceptsTab = false;
		this.table1.Add(this.tprezime);
		global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table1[this.tprezime]));
		w20.TopAttach = ((uint)(2));
		w20.BottomAttach = ((uint)(3));
		w20.LeftAttach = ((uint)(1));
		w20.RightAttach = ((uint)(2));
		w20.XOptions = ((global::Gtk.AttachOptions)(4));
		w20.YOptions = ((global::Gtk.AttachOptions)(4));
		this.Add(this.table1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 389;
		this.DefaultHeight = 420;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.studenti.Clicked += new global::System.EventHandler(this.Studenti);
		this.dodaj.Clicked += new global::System.EventHandler(this.dodajUcenika);
	}
}
