INSERT INTO a VALUES (1, 2, 1);
INSERT INTO a VALUES (1, 5, 9);
INSERT INTO a VALUES (2, 3, 3);
INSERT INTO a VALUES (3, 4, 2);

INSERT INTO b VALUES (1, 1, 1);
INSERT INTO b VALUES (1, 2, 1);
INSERT INTO b VALUES (3, 2, 7);
INSERT INTO b VALUES (4, 3, 2);
commit;