
// This file has been generated by the GUI designer. Do not modify.
namespace DomaciGTK
{
	public partial class Window
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label Ime;

		private global::Gtk.TextView Imet;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Label prezime;

		private global::Gtk.TextView Prezimet;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Label Skola;

		private global::Gtk.ComboBox combobox1;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Label label4;

		private global::Gtk.TextView Razredt;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView Fajl;

		private global::Gtk.Button DodajUcenika;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget DomaciGTK.Window
			this.Name = "DomaciGTK.Window";
			this.Title = global::Mono.Unix.Catalog.GetString("Ucenici");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child DomaciGTK.Window.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.Ime = new global::Gtk.Label();
			this.Ime.Name = "Ime";
			this.Ime.LabelProp = global::Mono.Unix.Catalog.GetString("Ime");
			this.hbox1.Add(this.Ime);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.Ime]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.Imet = new global::Gtk.TextView();
			this.Imet.CanFocus = true;
			this.Imet.Name = "Imet";
			this.Imet.AcceptsTab = false;
			this.hbox1.Add(this.Imet);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.Imet]));
			w2.Position = 1;
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.prezime = new global::Gtk.Label();
			this.prezime.Name = "prezime";
			this.prezime.LabelProp = global::Mono.Unix.Catalog.GetString("Prezime");
			this.hbox2.Add(this.prezime);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.prezime]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.Prezimet = new global::Gtk.TextView();
			this.Prezimet.CanFocus = true;
			this.Prezimet.Name = "Prezimet";
			this.Prezimet.AcceptsTab = false;
			this.hbox2.Add(this.Prezimet);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.Prezimet]));
			w5.Position = 1;
			this.vbox1.Add(this.hbox2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.Skola = new global::Gtk.Label();
			this.Skola.Name = "Skola";
			this.Skola.LabelProp = global::Mono.Unix.Catalog.GetString("Skola");
			this.hbox3.Add(this.Skola);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.Skola]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.combobox1 = global::Gtk.ComboBox.NewText();
			this.combobox1.Name = "combobox1";
			this.hbox3.Add(this.combobox1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.combobox1]));
			w8.Position = 1;
			this.vbox1.Add(this.hbox3);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Razred");
			this.hbox4.Add(this.label4);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.label4]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.Razredt = new global::Gtk.TextView();
			this.Razredt.CanFocus = true;
			this.Razredt.Name = "Razredt";
			this.Razredt.AcceptsTab = false;
			this.hbox4.Add(this.Razredt);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.Razredt]));
			w11.Position = 1;
			this.vbox1.Add(this.hbox4);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox4]));
			w12.Position = 3;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.Fajl = new global::Gtk.TextView();
			this.Fajl.CanFocus = true;
			this.Fajl.Name = "Fajl";
			this.Fajl.Editable = false;
			this.GtkScrolledWindow.Add(this.Fajl);
			this.vbox1.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
			w14.PackType = ((global::Gtk.PackType)(1));
			w14.Position = 4;
			// Container child vbox1.Gtk.Box+BoxChild
			this.DodajUcenika = new global::Gtk.Button();
			this.DodajUcenika.CanFocus = true;
			this.DodajUcenika.Name = "DodajUcenika";
			this.DodajUcenika.UseUnderline = true;
			this.DodajUcenika.Label = global::Mono.Unix.Catalog.GetString("DodajUcenika");
			this.vbox1.Add(this.DodajUcenika);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.DodajUcenika]));
			w15.PackType = ((global::Gtk.PackType)(1));
			w15.Position = 5;
			w15.Expand = false;
			w15.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 992;
			this.DefaultHeight = 558;
			this.Show();
			this.DodajUcenika.Clicked += new global::System.EventHandler(this.OnDodajUcenikaClicked);
		}
	}
}
